//
//  Consts.swift
//  Channers
//
//  Created by Rez on 4/12/23.
//

import Foundation


class AppConsts {
    static let allForums : [String] = [
        "3",
        "a",
        "aco",
        "adv",
        "an",
        "b",
        "bant",
        "biz",
        "c",
        "cgl",
        "ck",
        "cm",
        "co",
        "d",
        "diy",
        "e",
        "f",
        "fa",
        "fit",
        "g",
        "gd",
        "gif",
        "h",
        "hc",
        "his",
        "hm",
        "hr",
        "i",
        "ic",
        "int",
        "jp",
        "k",
        "lgbt",
        "lit",
        "m",
        "mlp",
        "mu",
        "n",
        "news",
        "o",
        "out",
        "p",
        "po",
        "pol",
        "pw",
        "qa",
        "qst",
        "r",
        "r9k",
        "s",
        "s4s",
        "sci",
        "soc",
        "sp",
        "t",
        "tg",
        "toy",
        "trash",
        "trv",
        "tv",
        "u",
        "v",
        "vg",
        "vip",
        "vm",
        "vmg",
        "vp",
        "vr",
        "vrpg",
        "vst",
        "vt",
        "w",
        "wg",
        "wsg",
        "wsr",
        "x",
        "xs",
        "y",
        "3",
        "a",
        "aco",
        "adv",
        "an",
        "b",
        "bant",
        "biz",
        "c",
        "cgl",
        "ck",
        "cm",
        "co",
        "d",
        "diy",
        "e",
        "f",
        "fa",
        "fit",
        "g",
        "gd",
        "gif",
        "h",
        "hc",
        "his",
        "hm",
        "hr",
        "i",
        "ic",
        "int",
        "jp",
        "k",
        "lgbt",
        "lit",
        "m",
        "mlp",
        "mu",
        "n",
        "news",
        "o",
        "out",
        "p",
        "po",
        "pol",
        "pw",
        "qa",
        "qst",
        "r",
        "r9k",
        "s",
        "s4s",
        "sci",
        "soc",
        "sp",
        "t",
        "tg",
        "toy",
        "trash",
        "trv",
        "tv",
        "u",
        "v",
        "vg",
        "vip",
        "vm",
        "vmg",
        "vp",
        "vr",
        "vrpg",
        "vst",
        "vt",
        "w",
        "wg",
        "wsg",
        "wsr",
        "x",
        "xs",
        "y"
    ]
    
    //a lit of nsfw forum tags
    static let nsfwForums : [String] = [
        "b",
        "r9k",
        "pol",
        "bant",
        "soc",
        "s4s",
        "s",
        "hc",
        "hm",
        "h",
        "e",
        "u",
        "d",
        "y",
        "t",
        "hr",
        "gif",
        "aco",
        "r"
    ]
    
    
}
//api heads for calling
class domains {
    ///This domain serves all 4chan API endpoints in the form of static json files.
    static let chanMain : String = "a.4cdn.org"
    
    ///This is the primary content domain used for serving user submitted media attached to posts.
    static let chanMedia : String = "i.4cdn.org"
    
    ///Serves all static site content including icons, banners, CSS and JavaScript files.
    static let chanStatic : String = "s.4cdn.org"
}


